set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'syntastic'
Plugin 'ervandew/supertab'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'hdima/python-syntax'
Plugin 'vim-scripts/boxdraw'
Plugin 'rust-lang/rust.vim'

call vundle#end()        
filetype plugin indent on

syntax on
set ignorecase
set smartcase
set backspace=indent,eol,start
set nostartofline
set autoindent
set ruler
set laststatus=2
set confirm
set number
set shiftwidth=4
set softtabstop=4
set expandtab
set mouse=a
set hlsearch
set cursorline

nnoremap j gj
nnoremap k gk
inoremap jk <esc>

"Python syntax highlighting:
"Syntastic
function! TPySyntasic()
    let g:syntastic_python_python_exec = '/Users/will/.pyenv/shims/python'
    let g:syntastic_python_checkers = ['pylint']
endfunc

"python-syntax
let python_highlight_all = 1
let python_version_2 = 1

"Enter line without going into insert mode
nmap <S-ENTER> O<Esc>
nmap <C-ENTER> o<Esc>
set fillchars+=vert:\

"80 column highlight
if exists('+colorcolumn')
  set colorcolumn=200
  highlight ColorColumn ctermbg=2
else
  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
endif
